apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sumologic.metadata.name.pvc-cleaner.roles.serviceaccount" . }}
  labels:
    app: {{ template "sumologic.labels.app.pvc-cleaner.roles.serviceaccount" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
  {{- with (dig "pvc-cleaner" "serviceAccount" "annotations" false (.Values | merge (dict))) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if (dig "pvc-cleaner" "job" "pullSecrets" false (.Values | merge (dict))) }}
imagePullSecrets:
{{ toYaml (dig "pvc-cleaner" "job" "pullSecrets" false (.Values | merge (dict))) | indent 2 }}
{{- end }}
